web:
  restart: always
  build: ./wordpress
  links:
    - db:mysql

db:
  image: mariadb
  environment:
    MYSQL_DATABASE: wordpress
    MYSQL_ROOT_PASSWORD: wordpress
    MYSQL_ALLOW_EMPTY_PASSWORD: "True"

nginx:
  restart: always
  build : ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - web
  links:
    - web:fpm
